export const ANALYTICS_EVENTS = {
  appOpened: "app_opened",
  bootstrapHydrated: "bootstrap_hydrated",
  onboardingStarted: "onboarding_started",
  onboardingCompleted: "onboarding_completed",
  scanStarted: "scan_started",
  cameraOpened: "camera_opened",
  cameraPermissionDenied: "camera_permission_denied",
  frontCaptured: "front_captured",
  backCaptured: "back_captured",
  retakeFront: "retake_front",
  retakeBack: "retake_back",
  cameraCaptureFailed: "camera_capture_failed",
  scanHandoffToProcessing: "scan_handoff_to_processing",
  scanUploaded: "scan_uploaded",
  scanCompleted: "scan_completed",
  cardAddedToCollection: "card_added_to_collection",
  aiChatOpened: "ai_chat_opened",
  aiMessageSent: "ai_message_sent",
  aiMessageFailed: "ai_message_failed",
  aiSuggestedPromptTapped: "ai_suggested_prompt_tapped",
  priceHistoryUpgradeTapped: "price_history_upgrade_tapped",
  activeMarketItemTapped: "active_market_item_tapped",
  activeMarketPreviewOpened: "active_market_preview_opened",
  priceHistoryPreviewOpened: "price_history_preview_opened",
  gradingOutlookPreviewOpened: "grading_outlook_preview_opened",
  resultsDetailRouteFailed: "results_detail_route_failed",
  askAiFromResults: "ask_ai_from_results",
  askAiFromHome: "ask_ai_from_home",
  askAiFromManageCard: "ask_ai_from_manage_card",
  addToCollectionFromResults: "add_to_collection_from_results",
  marketPulseViewed: "market_pulse_viewed",
  marketPulseItemOpened: "market_pulse_item_opened",
  providerFallbackUsed: "provider_fallback_used",
  paywallViewed: "paywall_viewed",
  paywallDismissed: "paywall_dismissed",
  paywallPurchaseStarted: "paywall_purchase_started",
  paywallPurchaseFailed: "paywall_purchase_failed",
  paywallRestoreFailed: "paywall_restore_failed",
  trialStarted: "trial_started",
  subscriptionStarted: "subscription_started",
  subscriptionRestored: "subscription_restored"
} as const;

export type AnalyticsEventName = (typeof ANALYTICS_EVENTS)[keyof typeof ANALYTICS_EVENTS];
